package com.cft.randomuser.models

data class UserUiModel(
    val gender: String? = null,
    val title: String? = null,
    val first: String? = null,
    val last: String? = null,
    val streetNumber: Int? = null,
    val streetName: String? = null,
    val city: String? = null,
    val state: String? = null,
    val country: String? = null,
    val postcode: String? = null,
    val latitude: String? = null,
    val longitude: String? = null,
    val timezoneOffset: String? = null,
    val timezoneDescription: String? = null,
    val email: String? = null,
    val uuid: String? = null,
    val username: String? = null,
    val password: String? = null,
    val salt: String? = null,
    val md5: String? = null,
    val sha1: String? = null,
    val sha256: String? = null,
    val registerDate: String? = null,
    val registerAge: Int? = null,
    val dobDate: String? = null,
    val dobAge: Int? = null,
    val phone: String? = null,
    val cell: String? = null,
    val idName: String? = null,
    val idValue: String? = null,
    val large: String? = null,
    val medium: String? = null,
    val thumbnail: String? = null,
    val nat: String? = null,
)
